gestionp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gestionpfe.urls',namespace='gestionpfe'))
]

gestionpfe/urls.py
from django.urls import path
from . import views

app_name="gestionpfe"
urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('DemandeStage/',views.demandeS,name='demandeS'),
    path('CahierCharge/',views.cahierC,name='demandeC'),

]

gestionpfe/models.py
from django.db import models

# Create your models here.

gestionpfe/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'index.html')

def login(request):
    return render(request,'register/login.html')

def signup(request):
    return render(request,'register/signup.html')

def demandeS(request):
    return render(request,'parts/demandeStage.html')

def cahierC(request):
    return render(request,'parts/CahierCharge.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
		<title>PFE</title>

		<!-- Favicons -->
		<link type="image/x-icon" href="{% static 'img/logo.png' %}" rel="icon">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- Fontawesome CSS -->
		<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css' %}">

		<!-- Swiper CSS -->
		<link rel="stylesheet" href="{% static 'plugins/swiper/css/swiper.min.css' %}">

		<!-- Main CSS -->
		<link rel="stylesheet" href="{% static 'css/style.css' %}">

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="{% static 'js/html5shiv.min.js"></script>
			<script src="{% static 'js/respond.min.js"></script>
		<![endif]-->

	</head>
	<body>

		<!-- Main Wrapper -->
		<div class="main-wrapper">
      {% include 'includes/header.html' %}
      {%  block content %}
      {% endblock content %}
      {% include 'includes/footer.html' %}

    </div>
<!-- /Main Wrapper -->

<!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>

<!-- Bootstrap Core JS -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- Swiper JS -->
<script src="{% static 'plugins/swiper/js/swiper.min.js' %}"></script>

<!-- Slick JS -->
<script src="{% static 'js/slick.js' %}"></script>

<!-- Custom JS -->
<script src="{% static 'js/script.js' %}"></script>

</body>

</html>

templates/includes/footer.html
{% load static %}
<footer class="footer">

  <!-- Footer Top -->
  <div class="footer-top">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-3 col-md-6">

          <!-- Footer Widget -->
          <div class="footer-widget footer-about">
            <div class="footer-logo">
              <img src="{% static 'img/footer-logo.png'  %}" alt="logo">
            </div>
            <div class="footer-about-content">
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
              <div class="social-icon">
                <ul>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-facebook-f"></i> </a>
                  </li>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-twitter"></i> </a>
                  </li>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                  </li>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
                  </li>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-dribbble"></i> </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <!-- /Footer Widget -->

        </div>

        <div class="col-lg-3 col-md-6">

          <!-- Footer Widget -->
          <div class="footer-widget footer-menu">
            <h2 class="footer-title">For Patients</h2>
            <ul>
              <li><a href="search.html">Search for Doctors</a></li>
              <li><a href="login.html">Login</a></li>
              <li><a href="register.html">Register</a></li>
              <li><a href="booking.html">Booking</a></li>
              <li><a href="patient-dashboard.html">Patient Dashboard</a></li>
            </ul>
          </div>
          <!-- /Footer Widget -->

        </div>

        <div class="col-lg-3 col-md-6">

          <!-- Footer Widget -->
          <div class="footer-widget footer-menu">
            <h2 class="footer-title">For Doctors</h2>
            <ul>
              <li><a href="appointments.html">Appointments</a></li>
              <li><a href="chat.html">Chat</a></li>
              <li><a href="login.html">Login</a></li>
              <li><a href="doctor-register.html">Register</a></li>
              <li><a href="doctor-dashboard.html">Doctor Dashboard</a></li>
            </ul>
          </div>
          <!-- /Footer Widget -->

        </div>

        <div class="col-lg-3 col-md-6">

          <!-- Footer Widget -->
          <div class="footer-widget footer-contact">
            <h2 class="footer-title">Contact Us</h2>
            <div class="footer-contact-info">
              <div class="footer-address">
                <span><i class="fas fa-map-marker-alt"></i></span>
                <p> 3556  Beech Street, San Francisco,<br> California, CA 94108 </p>
              </div>
              <p>
                <i class="fas fa-phone-alt"></i>
                +1 315 369 5943
              </p>
              <p class="mb-0">
                <i class="fas fa-envelope"></i>
                doccure@example.com
              </p>
            </div>
          </div>
          <!-- /Footer Widget -->

        </div>

      </div>
    </div>
  </div>
  <!-- /Footer Top -->

  <!-- Footer Bottom -->
          <div class="footer-bottom">
    <div class="container-fluid">

      <!-- Copyright -->
      <div class="copyright">
        <div class="row">
          <div class="col-md-6 col-lg-6">
            <div class="copyright-text">
              <p class="mb-0">&copy; 2020 Doccure. All rights reserved.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-6">

            <!-- Copyright Menu -->
            <div class="copyright-menu">
              <ul class="policy-menu">
                <li><a href="term-condition.html">Terms and Conditions</a></li>
                <li><a href="privacy-policy.html">Policy</a></li>
              </ul>
            </div>
            <!-- /Copyright Menu -->

          </div>
        </div>
      </div>
      <!-- /Copyright -->

    </div>
  </div>
  <!-- /Footer Bottom -->

</footer>

templates/includes/header.html
{% load static %}
<header class="header">
  <nav class="navbar navbar-expand-lg header-nav">
    <div class="navbar-header">
      <a id="mobile_btn" href="javascript:void(0);">
        <span class="bar-icon">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </a>
      <a href="index.html" class="navbar-brand logo">
        <img src="{% static 'img/logo.png' %}" class="img-fluid" alt="Logo">
      </a>
    </div>
    <div class="main-menu-wrapper">
      <div class="menu-header">
        <a href="index.html" class="menu-logo">
          <img src=" {% static 'img/logo.png' %}" class="img-fluid" alt="Logo">
        </a>
        <a id="menu_close" class="menu-close" href="javascript:void(0);">
          <i class="fas fa-times"></i>
        </a>
      </div>
      <ul class="main-nav">
        <li class="has-submenu active">
          <a href="#">Gestion PFE <i class="fas fa-chevron-down"></i></a>
          <ul class="submenu">
            <li><a href="{% url 'gestionpfe:demandeS' %}">demande de stage</a></li>
            <li><a href="{% url 'gestionpfe:demandeC' %}">cahier de charge</a></li>
            <li><a href="index-2.html">7ajaa</a></li>
            <li><a href="index-3.html">departement</a></li>
          </ul>
        </li>
        <li class="has-submenu">
          <a href="#"> Gestion CV <i class="fas fa-chevron-down"></i></a>
          <ul class="submenu">
            <li><a href="doctor-dashboard.html"> Création CV</a></li>
          </ul>
        </li>
        <li class="has-submenu">
          <a href="#">Gestion .... <i class="fas fa-chevron-down"></i></a>
          <ul class="submenu">
          </ul>
        </li>

        <li class="login-link">
          <a href="{% url 'gestionpfe:login' %}">Login / Signup</a>
        </li>
      </ul>
    </div>
    <ul class="nav header-navbar-rht">
      <li class="nav-item contact-item">
        <div class="header-contact-img">
          <i class="far fa-hospital"></i>
        </div>
        <div class="header-contact-detail">
          <p class="contact-header">Contact</p>
          <p class="contact-info-header"> +1 315 369 5943</p>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link header-login" href="{% url 'gestionpfe:login' %}">login / Signup </a>
      </li>
    </ul>
  </nav>

</header>

<!-- /Header -->

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="pharmacy-home-slider">
  <div class="swiper-container">
      <div class="swiper-wrapper">
          <div class="swiper-slide">
          </div>
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
      <div class="banner-wrapper">
      <div class="banner-header text-center">
        <h1>Search Doctor, Make an Appointment</h1>
        <p>Discover the best doctors, clinic & hospital the city nearest to you.</p>
      </div>
    </div>
  </div>
  <!-- Add Pagination -->
  <div class="swiper-pagination"></div>
</div>
<div class="card text-center">
  <div class="card-header">
    Coming Soon
  </div>
  <div class="card-body">
    <h5 class="card-title">gestion PFE</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">...............</a>
  </div>
  <div class="card-footer text-muted">
    2 days later
  </div>
</div>

{% endblock content %}

templates/parts/CahierCharge.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% endblock content %}

templates/parts/demandeStage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% endblock content %}

templates/register/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="content">
  <div class="container-fluid">

    <div class="row">
      <div class="col-md-8 offset-md-2">

        <!-- Login Tab Content -->
        <div class="account-content">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-12 col-lg-6 login-right">
              <div class="login-header">
                <h3>Login <span></span></h3>
              </div>
              <form action="https://doccure-html.dreamguystech.com/template/index.html">
                <div class="form-group form-focus">
                  <input type="email" class="form-control floating">
                  <label class="focus-label">Email</label>
                </div>
                <div class="form-group form-focus">
                  <input type="password" class="form-control floating">
                  <label class="focus-label">Password</label>
                </div>
                <div class="text-right">
                  <a class="forgot-link" href="forgot-password.html">Forgot Password ?</a>
                </div>
                <button class="btn btn-primary btn-block btn-lg login-btn" type="submit">Login</button>
                <div class="login-or">
                  <span class="or-line"></span>
                  <span class="span-or">or</span>
                </div>
                <div class="row form-row social-login">
                  <div class="col-6">
                    <a href="#" class="btn btn-facebook btn-block"><i class="fab fa-facebook-f mr-1"></i> Login</a>
                  </div>
                  <div class="col-6">
                    <a href="#" class="btn btn-google btn-block"><i class="fab fa-google mr-1"></i> Login</a>
                  </div>
                </div>
                <div class="text-center dont-have">Don’t have an account? <a href="{% url 'gestionpfe:signup' %}">Register</a></div>
              </form>
            </div>
          </div>
        </div>
        <!-- /Login Tab Content -->

      </div>
    </div>

  </div>

</div>

{% endblock content %}

templates/register/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="content">
  <div class="container-fluid">

    <div class="row">
      <div class="col-md-8 offset-md-2">

        <!-- Register Content -->
        <div class="account-content">
          <div class="row align-items-center justify-content-center">
          
            <div class="col-md-12 col-lg-6 login-right">
              <div class="login-header">
                <h3>Etudiant Register</h3>
              </div>

              <!-- Register Form -->
              <form action="https://doccure-html.dreamguystech.com/template/doctor-dashboard.html">
                <div class="form-group form-focus">
                  <input type="text" class="form-control floating">
                  <label class="focus-label">Name</label>
                </div>
                <div class="form-group form-focus">
                  <input type="text" class="form-control floating">
                  <label class="focus-label">Mobile Number</label>
                </div>
                <div class="form-group form-focus">
                  <input type="password" class="form-control floating">
                  <label class="focus-label">Create Password</label>
                </div>
                <div class="text-right">
                  <a class="forgot-link" href="login.html">Already have an account?</a>
                </div>
                <button class="btn btn-primary btn-block btn-lg login-btn" type="submit">Signup</button>
                <div class="login-or">
                  <span class="or-line"></span>
                  <span class="span-or">or</span>
                </div>
                <div class="row form-row social-login">
                  <div class="col-6">
                    <a href="#" class="btn btn-facebook btn-block"><i class="fab fa-facebook-f mr-1"></i> Login</a>
                  </div>
                  <div class="col-6">
                    <a href="#" class="btn btn-google btn-block"><i class="fab fa-google mr-1"></i> Login</a>
                  </div>
                </div>
              </form>
              <!-- /Register Form -->

            </div>
          </div>
        </div>
        <!-- /Register Content -->

      </div>
    </div>

  </div>

</div>


{% endblock content %}